hr/urls.py
from django.urls import path
from hr import views

urlpatterns=[

    path("",views.SignInView.as_view(),name="signin"),
    path("index",views.DashBoardView.as_view(),name="index"),
    path("signout",views.SignoutView.as_view(),name="signout"),
    path("category",views.CategoryListCeateView.as_view(),name="category"),
    path("category/<int:pk>/remove/",views.CategoryDeleteView.as_view(),name="category-delete"),
    path("job/add",views.JobCreateView.as_view(),name="job-add"),
    path("job/list",views.JobListView.as_view(),name="job-list"),
    path("job/<int:pk>/remove/",views.JobDeleteView.as_view(),name="job-delete"),
    path("job/<int:pk>/change/",views.JobUpdateView.as_view(),name="job-edit"),
    path("job/<int:pk>/applications/",views.JobApplicationListview.as_view(),name="job-application"),
    path("applications/<int:pk>/",views.AppllicationDetailView.as_view(),name="application-detail"),
    path("applications/<int:pk>/change/",views.ApplicationUpdateView.as_view(),name="application-edit"),

]

jobseeker/urls.py
from django.urls import path
from jobseeker import views

urlpatterns=[

    path("register/",views.SignupView.as_view(),name="signup"),
    path("signout/",views.SignoutView.as_view(),name="signout"),
    path("index/",views.StudentIndexView.as_view(),name="seeker-index"),
    path("profile/add/",views.ProfileCreateView.as_view(),name="profile-add"),
    path("profile/<int:pk>/",views.ProfileDetailView.as_view(),name="profile-detail"),
    path("profile/<int:pk>/change/",views.ProfileEditView.as_view(),name="profile-edit"),
    path("jobs/<int:pk>/detail/",views.JobDetailView.as_view(),name="job-detail"),
    path("jobs/<int:pk>/apply/",views.ApplyJobView.as_view(),name="job-apply"),
    path("applications/all/",views.ApplicationListView.as_view(),name="myapplications"),
    path("jobs/<int:pk>/save/",views.JobSaveView.as_view(),name="job-save"),
    path("jobs/saved/all/",views.SavedJobListView.as_view(),name="saved-jobs"),



]

placementapplication/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("hr.urls")),
    path("seeker/",include("jobseeker.urls"))


]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobseeker/models.py
from django.db import models

# Create your models here.

myapp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=200,unique=True)

    def __str__(self):
        return self.name
    
class Jobs(models.Model):
    title=models.CharField(max_length=200)
    description=models.CharField(max_length=200)
    salary=models.PositiveIntegerField()
    experience=models.PositiveIntegerField(default=0)
    last_date=models.DateField()
    vaccancies=models.PositiveIntegerField(default=1)
    poster=models.ImageField(upload_to="posterimages",null=True,blank=True)
    contact=models.CharField(max_length=200)
    qualification=models.CharField(max_length=200)
    category=models.ForeignKey(Category,on_delete=models.DO_NOTHING)
    status=models.BooleanField(default=True)
    company=models.CharField(max_length=200,null=True)
    created_date=models.DateTimeField(auto_now_add=True,null=True)
    options=(

        ("part-time","part-time"),
        ("full-time","full-time")

    )
    job_type=models.CharField(max_length=200,choices=options,default="full-time")

    def __str__(self):
        return self.title
    
    def application_count(self):
        qs=Applications.objects.filter(job=self).count()
        return qs
    
class StudentProfile(models.Model):
    qualification=models.CharField(max_length=200)
    resume=models.FileField(upload_to="resumes",null=True,blank=True)
    skills=models.CharField(max_length=200)
    age=models.PositiveIntegerField()
    options=(
        ("male","male"),("female","female")
    )
    gender=models.CharField(max_length=200,choices=options,default="male")
    experience=models.PositiveIntegerField(default=0)
    address=models.CharField(max_length=200)
    phone=models.CharField(max_length=200)
    profile_pic=models.ImageField(upload_to="profilepics",null=True,blank=True)
    user=models.OneToOneField(User,on_delete=models.CASCADE,related_name="profile")
    saved_jobs=models.ManyToManyField(Jobs,related_name="saved",null=True)


    def __str__(self):
        return self.user.username

class Applications(models.Model):
    job=models.ForeignKey(Jobs,on_delete=models.DO_NOTHING)
    student=models.ForeignKey(User,on_delete=models.CASCADE)
    applied_date=models.DateTimeField(auto_now_add=True)
    options=(
        ("pending","pending"),("rejected","rejected"),("processing","processing"),("shortlisted","shortlisted")
    )
    status=models.CharField(max_length=200,choices=options,default="pending")

class Projects(models.Model):
    name=models.CharField(max_length=200)
    description=models.CharField(max_length=200)
    git_link=models.CharField(max_length=200)
    user=models.ForeignKey(StudentProfile,on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.name




    

jobseeker/forms.py
from django import forms

from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from myapp.models import StudentProfile

class RegistrationForm(UserCreationForm):

    class Meta:
        model=User
        fields=["username","email","password1","password2","first_name"]


class ProfileForm(forms.ModelForm):

    class Meta:
        model=StudentProfile
        exclude=("user",)

jobseeker/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render,redirect
from django.urls import reverse_lazy
from django.contrib.auth import logout
from django.views.generic import View,CreateView,TemplateView,DetailView,UpdateView,ListView
from myapp.models import StudentProfile,Jobs,Applications,Category
from jobseeker.forms import RegistrationForm,ProfileForm
from django.views.decorators.cache import never_cache
from django.utils.decorators import method_decorator
from django.contrib import messages



def signin_required(fn):

    def wrapper(request,*args,**kwargs):

        if not request.user.is_authenticated:
            messages.error(request,"signin required")
            return redirect("signin")
        else:
            return fn(request,*args,**kwargs)
    return wrapper

decs=[never_cache,signin_required]


class SignupView(CreateView):

    template_name="jobseeker/register.html"
    form_class=RegistrationForm
    success_url=reverse_lazy("signin")

@method_decorator(decs,name="dispatch")
class SignoutView(View):

    def get(self,request,*args,**kwargs):

        logout(request)
        return redirect("signin")

@method_decorator(decs,name="dispatch")
class StudentIndexView(ListView):

    template_name="jobseeker/index.html"
    context_object_name="data"
    model=Jobs

    def get_queryset(self):
        my_applications=Applications.objects.filter(student=self.request.user).values_list("job",flat=True)
        qs=Jobs.objects.exclude(id__in=my_applications).order_by("-created_date")
        if "category" in self.request.GET:
            category_value=self.request.GET.get("category")
            qs=qs.filter(category__name=category_value)
            print(category_value)
        return qs

    def get_context_data(self, **kwargs):

        context=super().get_context_data(**kwargs)
        qs=Category.objects.all()
        context["categories"]=qs
        return context
        
@method_decorator(decs,name="dispatch")
class ProfileCreateView(CreateView):

    template_name="jobseeker/profile_add.html"
    form_class=ProfileForm
    success_url=reverse_lazy("seeker-index")

    def form_valid(self,form):
        form.instance.user=self.request.user
        return super().form_valid(form)

@method_decorator(decs,name="dispatch")
class ProfileDetailView(DetailView):

    template_name="jobseeker/profile_detail.html"
    context_object_name="data"
    model=StudentProfile

@method_decorator(decs,name="dispatch")
class ProfileEditView(UpdateView):

    template_name="jobseeker/profile_edit.html"
    form_class=ProfileForm
    model=StudentProfile
    success_url=reverse_lazy("seeker-index")

@method_decorator(decs,name="dispatch")
class JobDetailView(DetailView):

    template_name="jobseeker/job_detail.html"
    model=Jobs
    context_object_name="data"

@method_decorator(decs,name="dispatch")
class ApplyJobView(View):

    def post(self,request,*args,**kwargs):
        id=kwargs.get("pk")
        job_object=Jobs.objects.get(id=id)
        student_object=request.user
        Applications.objects.create(job=job_object,student=student_object)
        return redirect("seeker-index")

@method_decorator(decs,name="dispatch")    
class ApplicationListView(ListView):

    template_name="jobseeker/applications.html"
    model=Applications
    context_object_name="data"

    def get_queryset(self):
        
        qs=Applications.objects.filter(student=self.request.user)
        return qs

@method_decorator(decs,name="dispatch")
class JobSaveView(View):

    def post(self,request,*args,**kwargs):

        id=kwargs.get("pk")
        job_object=Jobs.objects.get(id=id)
        action=request.POST.get("action")
        if action=="save":
            request.user.profile.saved_jobs.add(job_object)
        elif action=="unsave":
            request.user.profile.saved_jobs.remove(job_object)
        return redirect("seeker-index")

@method_decorator(decs,name="dispatch")    
class SavedJobListView(ListView):

    model=StudentProfile

    def get(self,request,*args,**kwargs):

        qs=request.user.profile.saved_jobs.all()
        return render(request,"jobseeker/saved_jobs.html",{"data":qs})

jobseeker/templates/jobseeker/applications.html
{%extends "jobseeker/base.html"%}
{%block bodyblock%}
{% load static %}
<div>

</div>
{%if form.errors%}
{{form.errors}}
{%endif%}

<div class="row">
    <div class="col-2 bg-light ">
        <div class="mt-5 mx-2">
        </div>
    </div>
    <div class="col-8 ps-4 pt-5 bg-light">
        <div class="">
            <div class="container-fluid">
                <form class="d-flex" role="search">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-dark" type="submit">Search</button>
                </form>
            </div>
            <hr class="border-3 w-25 d-flex justify-content-center"><br>
        </div>
        {%for application in data%}
        <div class="card mb-3">
            <div class="row g-0">
                <div class="col-md-3">
                    {%if application.job.poster%}
                    <div class="d-flex justify-content-center align-content-around mt-4">
                        <img src="{{application.job.poster.url}}" class="" style="width: 50%;height: fit-content;object-fit:cover;">

                    </div>
                    {%else%}
                    <div class="d-flex justify-content-center align-content-around mt-4">
                        <img src="{% static 'jobseeker/images/hiring.jpg' %}" class="" style="width: 50%;height: fit-content;object-fit:cover;">
                    </div>
                    {%endif%}
                </div>
                <div class="col-md-6">
                    <div class="card-body">
                        <h5 class="card-title">{{application.job.title}}</h5>
                        <p>Company:{{application.job.company}}</p>
                        <p>Vaccancies:{{application.job.vaccancies}}</p>
                        <p>Last Date:{{application.job.last_date}}</p>
                        <p>status:{{application.status}}</p>


                    </div>
                </div>
                <div class="col-md-3 d-flex align-items-center justify-content-center flex-column ">
                    <div class="">
                        <p>Applications:{{application.job.application_count}}</p>
                    </div>
                </div>
            </div>
        </div>
        {%endfor%}
    </div>
    <div class="col-2 bg-light ">
        <div class="mt-5 mx-2">
        </div>
    </div>
</div>


{%endblock%}

jobseeker/templates/jobseeker/base.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>link sphere</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>

    <script src="https://cdn.jsdelivr.net/gh/alpinejs/alpine@v2.x.x/dist/alpine.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer"/>
    <link rel="stylesheet" href="{%static 'jobseeker/css/index.css'%}">
</head>
<body>
    <!-- nav starts -->
    <nav class="navbar fixed-top  p-0 mb-5" style="background-color: rgb(20, 10, 12);" >
        <div class="container-fluid">
          <a class="navbar-brand" href="#">
            <img src="{%static 'jobseeker/images/linkspherena.png'%}" alt="Logo" width="100" height="h-auto" class="ms-5">
          </a>

          <!-- search start -->
            <div class="container mt-3 w-50 mb-2">
                <div class="row justify-content-center">
                <div class="col-lg-6">
                    <form class="d-flex">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button type="submit" class="button btn btn-outline-light">search</button>
                    </form>
                </div>
                </div>
            </div>
        <!-- search end -->

            <a href="post_form.html"><i class="fa-regular fa-square-plus me-4 fs-3 text-white opacity-75"></i></a>

        <!-- profile dropdown start -->

        <div class="dropdown nav-item mr-lg-4" style="margin-right: 6em;">
            <a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle">
                {%if request.user.profile.profile_pic%}

                <img class="profile-small" src="{{request.user.profile.profile_pic.url}}" alt="Avatar">

                {%else%}

                <img class="profile-small" src="{%static 'jobseeker/images/profilepic.png'%}" alt="Avatar">

                {%endif%}

                <!-- <b class="caret"></b> -->
            </a>
            <ul class="dropdown-menu p-2" role="menu">
                {%if request.user.profile%}
                <li class="nav-item">
                    <a href="{%url 'profile-detail' request.user.profile.id%}" class="nav-link scroll">Profile</a>
                </li>
                <li class="nav-item">
                    <a href="{%url 'profile-edit' request.user.profile.id%}" class="nav-link scroll">Edit profile</a>
                </li>
                <div class="dropdown-divider"></div>
                {%else%}
                <li class="nav-item">
                    <a href="{%url 'profile-add'%}" class="nav-link scroll">Add profile</a>
                </li>
                <div class="dropdown-divider"></div>
                {%endif%}
                <li class="nav-item">
                    <a href="{%url 'myapplications'%}" class="nav-link scroll">Applications</a>
                </li>
                <li class="nav-item">
                    <a href="{%url 'saved-jobs'%}" class="nav-link scroll">Saved jobs</a>
                </li>
                <div class="dropdown-divider"></div>
                <li class="nav-item">
                    <a href="{%url 'signin'%}" class="nav-link scroll">Logout</a>
                </li>
            </ul>
        </div>
                    <!-- profile dropdown end -->


    </nav>
    <!-- nav ends -->

    <div class="container mt-5">

        {%block categoryblock%}

        {%endblock%}
    </div>

    <div class="container d-flex flex-column justify-content-center align-items-center mt-5">

        {%block bodyblock%}

        {%endblock%}

       

        
        
    </div>
</body>
</html>

jobseeker/templates/jobseeker/index.html
{%extends 'jobseeker/base.html'%}

{%block categoryblock%}

<div class="mt-5">.</div>

<div class="row mt-5">
  {%for cat in categories%}

  <div class="col-3">
    <a href="{%url 'seeker-index'%}?category={{cat.name}}">{{cat.name}}</a>({{cat.jobs_set.all.count}}jobs)
  </div>

  {%endfor%}
</div>

{%endblock%}

{%block bodyblock%}


{%for job in data%}


<div class="card mb-3 mt-5" style="max-width: 540px;">
    <div class="row g-0">
      <div class="col-md-4 d-flex justify-content-center align-items-center px-2">
        {%if job.poster%}
        <img src="{{job.poster.url}}" class="img-fluid rounded" alt="..." height="100%" width="300px">
        {%endif%}
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title">{{job.title}}</h5>
          <p class="card-text">

            <i class="fa-solid fa-clock" style="color: black;"></i> {{job.job_type}}
            <i class="fa-solid fa-sack-dollar" style="color: #000000;"></i> {{job.salary}}
            <i class="fa-solid fa-building" style="color: #000000;"></i> {{job.company}}

          </p>

        {%if request.user.profile%}

          <form action="{%url 'job-save' job.id%}" method="post">
            {%csrf_token%}
              {%if job in request.user.profile.saved_jobs.all%}
              <button type="submit" name="action" value="unsave" class="btn"><i class="fa-solid fa-bookmark" style="color: #000000;"></i></button>
              {%else%}
              <button type="submit" name="action" value="save" class="btn"><i class="fa-regular fa-bookmark" style="color: #000000;"></i></button>
              {%endif%}
          </form>

        {%endif%}

          <div class="mt-3">
            <a href="{%url 'job-detail' job.id%}" class="btn btn-outline-dark btn-sm">view more</a>
            <p class="card-text"><small class="text-body-secondary">Last updated 3 mins ago</small></p>
          </div>
          
        </div>
      </div>
    </div>
  </div>

{%endfor%}


{%endblock%}

jobseeker/templates/jobseeker/job_detail.html
{%extends 'jobseeker/base.html'%}

{%block bodyblock%}

<div class="card mt-5" style="width:80%" >
    <div class="row">
        <div class="col-4 d-flex align-items-center">
            {%if data.poster%}
            <img src="{{data.poster.url}}" class="rounded" alt="..." width="100%">
            {%endif%}
        </div>
        <div class="col-8">

            <div class="card-body">
                <h5 class="card-title fw-bolder">{{data.title}}</h5>
                <p class="card-text">Description:{{data.description}}
                </p>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item">salary:{{data.salary}}</li>
                <li class="list-group-item">Experience:{{data.experience}}</li>
                <li class="list-group-item">Last Date:{{data.last_date}}</li>
                <li class="list-group-item">Vaccancies:{{data.vaccancies}}</li>
                <li class="list-group-item">Contact:{{data.contact}}</li>
                <li class="list-group-item">Qualification:{{data.qualification}}</li>
                <li class="list-group-item">category:{{data.category}}</li>
                <li class="list-group-item">company:{{data.company}}</li>
                <li class="list-group-item">Job type:{{data.job_type}}</li>






            </ul>
            <div class="card-body d-flex justify-content-center">
                <form action="{%url 'job-apply' data.id%}" method="post">
                    {%csrf_token%}
                    <button type="submit">Apply</button>
                </form>
            </div>
        </div>
    </div>
</div>

{%endblock%}

jobseeker/templates/jobseeker/job_list.html
{%extends 'jobseeker/base.html'%}

{%block bodyblock%}

{{jobs}}

{%endblock%}

jobseeker/templates/jobseeker/profile_add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <div class="container">

        <form action="" method="post" enctype="multipart/form-data">

            {%csrf_token%}
            {{form.as_p}}

            <button type="submit">Add</button>
            
        </form>
    </div>

</body>
</html>

jobseeker/templates/jobseeker/profile_detail.html
{%extends 'jobseeker/base.html'%}

{%block bodyblock%}

    <div class="container mt-5 d-flex justify-content-center">

        <div class="card" style="width:50%">
            {%if data.profile_pic%}
                <img src="{{data.profile_pic.url}}" class="card-img-top" alt="..." height="300px">
            {%endif%}
            <div class="card-body">
              <h5 class="card-title fw-bolder">{{data.user.profile}}</h5>
              <p class="card-text">
                Address:{{data.address}}
                Phone:{{data.phone}}
                Email:{{data.user.email}}
              </p>
            </div>
            <ul class="list-group list-group-flush">
              <li class="list-group-item">Experience:{{data.experience}}</li>
              <li class="list-group-item">Gender:{{data.gender}}</li>
              <li class="list-group-item">Qualification:{{data.qualification}}</li>
            </ul>
            <div class="card-body">
                {%if data.resume%}

                    <a href="{{data.resume.url}}" download class="btn btn-outline-dark">Download cv</a>

                {%endif%}
            </div>
          </div>

    </div>

{%endblock%}

jobseeker/templates/jobseeker/profile_edit.html
{%extends 'jobseeker/base.html'%}

{%block bodyblock%}

{%if form.errors%}
{{form.errors}}
{%endif%}
<div class="container d-flex justify-content-around">
    <form action="" method="post" class="bg-white m-5 p-5 w-75 rounded-3" enctype="multipart/form-data">
       {%csrf_token%}
        <p class="fw-bold fs-4 ">Student Register</p>
        <hr class="mb-5 w-25 border-4">
        <div class=" row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-12 "><label for="">Full Name :</label><input
                    type="text" name="first_name" value="{{form.first_name.value}}" class="form-control"></div>
            <div class="col-lg-6 col-md-6 col-sm-12 col-12 mt-4"><label for="">Gender :</label>
                {{form.gender}}
            </div>
            <div class="col-lg-6 col-md-6 col-sm-12 col-12 mt-4">
                <label class="" for="">Qualification
                    :</label>
                    <input type="text" name="qualification" value="{{form.qualification.value}}" class="form-control"></div>

            <div class="col-lg-6 col-md-6 col-sm-12 col-12 mt-4">
                <label class="" for="">Profile Picture
                    :</label>
                   {{form.profile_pic}}
                </div>
            <div class="col-lg-6 col-md-6 col-sm-12 col-12 mt-4"><label class="" for="">Resume :</label>
               {{form.resume}}
                </div>
            <div class="col-lg-4 col-md-6 col-sm-12 col-12 mt-4">
                <label class="" for="">Phone :</label>
                <input type="number" name="phone" value="{{form.phone.value}}" class="form-control"></div>
            <div class="col-lg-4 col-md-6 col-sm-12 col-12 mt-4"><label class="" for="">Experience :</label>
                <input
                    type="text" name="experience" value="{{form.experience.value}}" class="form-control"></div>
            <div class="col-lg-4 col-md-6 col-sm-12 col-12 mt-4">
                <label class="" for="">DOB :

            </label>
            {{form.age}}
        </div>
            <div class="col-lg-6 col-md-6 col-sm-12 col-12 mt-4"><label class="" for="">Skills :</label>
                <textarea name="skills"
                    class="form-control">
                    {{form.skills.value}}
                </textarea></div>
            <div class="col-lg-6 col-md-6 col-sm-12 col-12 mt-4"><label class="" for="">Address :</label>
                <textarea
                    class="form-control" name="address">
                    {{form.address.value}}
                </textarea></div>
<div class="text-center">
<button class="btn btn-dark mt-4 mb-4 w-50">Edit</button>
   
</div>


        </div>
    </form>
</div>




{%endblock%}

jobseeker/templates/jobseeker/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <div class="container">
        
        <h1>Register</h1>

        <form action="" method="post">
            {%csrf_token%}
            {{form.as_p}}
            <button type="submit">Register</button>

        </form>
    </div>
</body>
</html>

jobseeker/templates/jobseeker/saved_jobs.html
{%extends 'jobseeker/base.html'%}

{%block bodyblock%}

<h4 class="mt-5">{{data|length}} saved jobs</h4>

{%for job in data%}


<div class="card mb-3 mt-5" style="max-width: 540px;">
    <div class="row g-0">
      <div class="col-md-4 d-flex justify-content-center align-items-center px-2">
        {%if job.poster%}
        <img src="{{job.poster.url}}" class="img-fluid rounded" alt="..." height="100%" width="300px">
        {%endif%}
      </div>
      <div class="col-md-8">
        <div class="card-body">
          <h5 class="card-title">{{job.title}}</h5>
          <p class="card-text">

            <i class="fa-solid fa-clock" style="color: black;"></i> {{job.job_type}}
            <i class="fa-solid fa-sack-dollar" style="color: #000000;"></i> {{job.salary}}
            <i class="fa-solid fa-building" style="color: #000000;"></i> {{job.company}}

          </p>

        {%if request.user.profile%}

          <form action="{%url 'job-save' job.id%}" method="post">
            {%csrf_token%}
              {%if job in request.user.profile.saved_jobs.all%}
                <button type="submit" name="action" value="unsave" class="btn"><i class="fa-solid fa-bookmark" style="color: #000000;"></i></button>
              {%else%}
                <button type="submit" name="action" value="save" class="btn"><i class="fa-regular fa-bookmark" style="color: #000000;"></i></button>
              {%endif%}
          </form>

        {%endif%}

          <div class="mt-3">
            <a href="{%url 'job-detail' job.id%}" class="btn btn-outline-dark btn-sm">view more</a>
            <p class="card-text"><small class="text-body-secondary">Last updated 3 mins ago</small></p>
          </div>
          
        </div>
      </div>
    </div>
  </div>

{%endfor%}


{%endblock%}